// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByzhYiW73QJkFCNR4L4XL_FvrHY1LV97s',
    appId: '1:1022794126931:web:c57598ee8cbed30bdb18a6',
    messagingSenderId: '1022794126931',
    projectId: 'my-notes-app-21e4b',
    authDomain: 'my-notes-app-21e4b.firebaseapp.com',
    storageBucket: 'my-notes-app-21e4b.firebasestorage.app',
    measurementId: 'G-JPW0908DC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcW9HwQ-uKEk3nRRTagBNE8Nz94DiNLgM',
    appId: '1:1022794126931:android:23059bf178facb29db18a6',
    messagingSenderId: '1022794126931',
    projectId: 'my-notes-app-21e4b',
    storageBucket: 'my-notes-app-21e4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSVSiyB7JNhvcYNsv4nR9HrrVK4HPZv80',
    appId: '1:1022794126931:ios:db1b30c9c11ca923db18a6',
    messagingSenderId: '1022794126931',
    projectId: 'my-notes-app-21e4b',
    storageBucket: 'my-notes-app-21e4b.firebasestorage.app',
    iosBundleId: 'com.example.myNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSVSiyB7JNhvcYNsv4nR9HrrVK4HPZv80',
    appId: '1:1022794126931:ios:db1b30c9c11ca923db18a6',
    messagingSenderId: '1022794126931',
    projectId: 'my-notes-app-21e4b',
    storageBucket: 'my-notes-app-21e4b.firebasestorage.app',
    iosBundleId: 'com.example.myNotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByzhYiW73QJkFCNR4L4XL_FvrHY1LV97s',
    appId: '1:1022794126931:web:945f13f6db0c15fddb18a6',
    messagingSenderId: '1022794126931',
    projectId: 'my-notes-app-21e4b',
    authDomain: 'my-notes-app-21e4b.firebaseapp.com',
    storageBucket: 'my-notes-app-21e4b.firebasestorage.app',
    measurementId: 'G-JDT66197RX',
  );
}
